In [32]:
import torch
import torch.nn as nn
a=torch.normal(0,1,size=(3,1))
b=torch.normal(0,1,size=(3,4))
print(a)
print(b)
print(a*b)

tensor([[-0.4075],
        [ 0.0516],
        [-0.6225]])
tensor([[-1.2657,  0.9715, -0.0522,  0.4691],
        [ 0.1612,  0.3254, -0.3914,  0.6854],
        [-1.6571,  0.3104, -0.7702,  0.8384]])
tensor([[ 0.5158, -0.3959,  0.0213, -0.1912],
        [ 0.0083,  0.0168, -0.0202,  0.0354],
        [ 1.0316, -0.1933,  0.4795, -0.5219]])
